# SPDX-FileCopyrightText: 2021-2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
path_classifiers:
    library:
    test:
        - tests
    exclude:
        - "**/subprojects/**"
        - tests/input
        - tests/new_input

extraction:
    cpp:
        prepare:
            packages:
                - meson
                - libcjson
                - libopenssl
        configure:
            command:
                - meson build
                - cd build
        index:
            build_command:
                - cd build
                - ninja all

