# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

math(EXPR ${CMAKE_PROJECT_NAME}_BITWISE_VERSION "${${CMAKE_PROJECT_NAME}_VERSION_MAJOR} << 16 | ${${CMAKE_PROJECT_NAME}_VERSION_MINOR} << 8 | ${${CMAKE_PROJECT_NAME}_VERSION_PATCH}" OUTPUT_FORMAT HEXADECIMAL)
