# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: Code Format Check

on:
  pull_request:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'LICENSE'
      - 'NOTICE'
      - '**.md'
      - '.gitignore'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
  schedule:
    - cron: '12 9 * * 3'

jobs:
  test:
    uses: xmidt-org/.github/.github/workflows/c-code-format.yml@main
